# Needed for keeping JDK 8
dist: trusty

before_install:
  - wget https://downloads.apache.org/maven/maven-3/3.6.3/binaries/apache-maven-3.6.3-bin.tar.gz
  - tar xzvf apache-maven-3.6.3-bin.tar.gz
  - export PATH=`pwd`/apache-maven-3.6.3/bin:$PATH
language: java
jdk:
  - openjdk8
cache:
  directories:
    - $HOME/.m2
script: mvn install -B -q
